In [1]:
import numpy as np

In [23]:
x = np.array([
    [0,0,1],
    [0,1,1],
    [1,0,1],
    [1,1,1]
])

In [24]:
y = np.array([
    [0],
    [1],
    [1],
    [0]
])

In [25]:
print(x)
print(y)

[[0 0 1]
 [0 1 1]
 [1 0 1]
 [1 1 1]]
[[0]
 [1]
 [1]
 [0]]


In [34]:
num_epochs = 10000000
syn0 = 2*np.random.random([3,4])-1
syn1 = 2*np.random.random([4,1])-1

In [32]:
print(syn0)
print(syn1)

[[-0.20134651 -0.28831442 -0.28749706 -0.56105084]
 [-0.42925051 -0.6140813  -0.30248887  0.94933731]
 [ 0.5542272   0.10702402 -0.99475673 -0.73671454]]
[[-0.47972939]
 [ 0.04271612]
 [ 0.50452716]
 [ 0.82619037]]


In [28]:
def nonlin(x, deriv = False):  
    if(deriv == True):  
        return x*(1-x)  
    return 1/(1+np.exp(-x))  
  

In [21]:
l2

array([[ 0.57538828],
       [ 0.55543033],
       [ 0.55346601]])

In [ ]:
for j in range(num_epochs):
    #feed forward through layers 0 ,1 and 2
    l0 = x
    l1 = nonlin(np.dot(l0,syn0))
    l2 = nonlin(np.dot(l1,syn1))
    #how much did we miss the target value?
    l2_error = y -l2
    if(j%10000) == 0:
        print('error:'+str(np.mean(np.abs(l2_error))))
    #in what direction is the target value?
    l2_delta = l2_error * nonlin(l2,deriv=True)
    #how much did each l1 value conrubute to l2 error?
    l1_error = l2_delta.dot(syn1.T)
    l1_delta = l1_error * nonlin(l1,deriv=True)
    syn1 += l1.T.dot(l2_delta)
    syn0 += l0.T.dot(l1_delta)
print(syn0)
print(syn1)

error:0.503865387156
error:0.0089079466183
error:0.00600989779113
error:0.0048109592744
error:0.00411777067383
error:0.00365339582626
error:0.00331497993871
error:0.00305447898194
error:0.00284607889293
error:0.00267452157052
error:0.00253013913215
error:0.00240647212586
error:0.00229902026366
error:0.00220454004993
error:0.00212062729919
error:0.00204545740292
error:0.00197761745463
error:0.00191599417408
error:0.00185969696972
error:0.00180800382749
error:0.00176032243559
error:0.00171616172447
error:0.00167511067912
error:0.00163682232602
error:0.00160100146543
error:0.00156739515646
error:0.00153578525397
error:0.00150598249425
error:0.00147782176381
error:0.00145115828136
error:0.00142586449196
error:0.00140182752161
error:0.00137894707649
error:0.00135713369803
error:0.00133630730473
error:0.0013163959667
error:0.00129733487019
error:0.00127906543842
error:0.00126153458147
error:0.00124469405352
error:0.00122849989965
error:0.00121291197794
error:0.00119789354497
error:0.00118341

In [33]:
for j in range(num_epochs):
    #feed forward through layers 0 ,1 and 2
    l0 = x
    l1 = nonlin(np.dot(l0,syn0))
    l2 = nonlin(np.dot(l1,syn1))
    #how much did we miss the target value?
    l2_error = y -l2
    if(j%10000) == 0:
        print('error:'+str(np.mean(np.abs(l2_error))))
    #in what direction is the target value?
    l2_delta = l2_error * nonlin(l2,deriv=True)
    #how much did each l1 value conrubute to l2 error?
    l1_error = l2_delta.dot(syn1.T)
    l1_delta = l1_error * nonlin(l1,deriv=True)
    syn1 += l1.T.dot(l2_delta)
    syn0 += l0.T.dot(l1_delta)
print(syn0)
print(syn1)

error:0.498927238003
error:0.00960797542262
error:0.00662578350428
error:0.00535203253622
error:0.00460540902427
error:0.00410112344145
[[-5.0255041  -0.36580453  4.62287014 -6.80181655]
 [ 5.17024083 -0.26529231 -4.7229372   6.77318806]
 [ 2.85278198  0.1989948  -2.68227476 -3.51937946]]
[[ -6.95762916]
 [  0.44628499]
 [  7.08701836]
 [ 12.68599811]]
