In [29]:
import numpy as np
def sigmoid(x):
    return 1/(1+np.exp(-x))

In [30]:
N_input = 4
N_hidden = 3
N_output = 2

In [31]:
np.random.seed(42)

In [32]:
X = np.random.randn(4)
print (X)

[ 0.49671415 -0.1382643   0.64768854  1.52302986]


In [33]:
weights_input_to_hidden = np.random.normal(0, scale = 0.1, size = (N_input, N_hidden))
print(weights_input_to_hidden)

[[-0.02341534 -0.0234137   0.15792128]
 [ 0.07674347 -0.04694744  0.054256  ]
 [-0.04634177 -0.04657298  0.02419623]
 [-0.19132802 -0.17249178 -0.05622875]]


权重矩阵

In [34]:
weights_hidden_to_output= np.random.normal(0,scale=0.1,size=(N_hidden,N_output))
print(weights_hidden_to_output)

[[-0.10128311  0.03142473]
 [-0.09080241 -0.14123037]
 [ 0.14656488 -0.02257763]]


In [35]:
hidden_layer_in = np.dot(X,weights_input_to_hidden)
print(hidden_layer_in)

[-0.34365494 -0.29801368  0.00097362]


In [36]:
hidden_layer_out = sigmoid(hidden_layer_in)
print(hidden_layer_out)

[ 0.41492192  0.42604313  0.5002434 ]


In [37]:
output_layer_in = np.dot(hidden_layer_out,weights_hidden_to_output)
print(output_layer_in)

[-0.00739221 -0.05842573]


In [38]:
output_layer_out = sigmoid(output_layer_in)
print(output_layer_out)

[ 0.49815196  0.48539772]
